version: '2.3'

services:
  cli:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    image: &cli-image cli 
    volumes:
      - ./:/app:delegated
    volumes_from: 
      - container:amazeeio-ssh-agent 
